### ISSUE TITLE
Provide a decline all non essential option from the first screen

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/cookie-policy#116]
It was pointed out that it would be better for people that want to decline cookies. If they could set that from the notice instead of coding manage and scrolling all the way down.

**Comment by pmahnke** [comment]
@anthonydillon I spoke to @wgx about this.  It would require someone to talk to marketing and legal about it, design it, reword it, etc.  As far as I know, @wgx is the only person asking for it right now. I am not opposed, but it is pretty far down my list of priorities.

**Comment by wgx** [comment]
@pmahnke also pointed out that a good proportion of those who object are likely also using ublock - and probably never see the cookie banner at all, which I accept. :)

**Comment by anthonydillon** [comment]
@wgx our cookie policy is not blocked by ublock as it is bespoke to Canonical.

@pmahnke I filed this from a [request from the community](https://twitter.com/mateosalta42/status/1363001466496155649).

**Comment by cassiocassio** [comment]
Can I ask if we have any way of knowing what %  of the users who choose "Manage" then choose "Only essential" ?

If it's a large majority - my guess - then this proposal would make most people happy, with fewer clicks and scrolling.

Manage is a pretty good pseudonym for "I'm very interested in understanding your cookie policies in detail" - those users want all the granularity and links to the policy and toggle switches.

We could put the "Manage..." button last, rename it to simply, and use the ... to indicate it will require more decisions.

<img width="699" alt="essential only" src="https://user-images.githubusercontent.com/4593556/108747608-87621280-7535-11eb-9a89-5bc531f64489.png">

**Comment by pmahnke** [comment]
Let's do this _after_ we confirm with KO.

**Comment by carkod** [comment]
@cassiocassio @anthonydillon any idea if this has been confirmed with KO?

**Comment by anthonydillon** [comment]
I don't think this is very important anymore. People are more familiar with the mechanism now.

**Comment by carkod** [comment]
ok, Closing then
