### ISSUE TITLE
https://web.dev/measure/ is complaining aria-hidden="true"

### ISSUE THREAD

**Issue by solazio** [canonical-web-and-design/cookie-policy#118]
We do this https://github.com/canonical-web-and-design/cookie-policy/search?q=aria-hidden
and https://web.dev/measure/ is complaining about it.
![image](https://user-images.githubusercontent.com/40214246/112482236-bd322b00-8d6f-11eb-874d-8725d7f99e93.png)

**Comment by SirSamTumless** [comment]
@solazio Please triage this accordingly.

**Comment by steverydz** [comment]
Fixed b y https://github.com/canonical-web-and-design/cookie-policy/pull/123
