### ISSUE TITLE
Styling issues when Vanilla versions are misaligned

### ISSUE THREAD

**Issue by bartaz** [canonical-web-and-design/cookie-policy#129]
`cookie-policy` includes it's own version of Vanilla and builds its own separate stylesheet with it.
When used in a project that also has Vanilla this means there are 2 Vanilla stylesheets on one website. This can cause issues when these versions don't match.

This happened recently with (fairly unnoticable) issue with modal spacing:

<img width="883" alt="Screenshot 2021-11-04 at 09 32 08" src="https://user-images.githubusercontent.com/83575/140282376-3fedd2d4-29e5-41ba-8126-639d7f5fa779.png">

Caused by the fact that cookie-policy is using older version of Vanilla than the websites.
The issue above will be fixed by merging renovate PR  #127, but renovate only updates cookie-policy once a month, so this leaves quite a large window of possibly broken experience.

Ideally `cookie-policy` should not include its own version of Vanilla and rely on version in the project.

We could also update renovate config here to make sure Vanilla is updated immediately when released.

**Comment by anthonydillon** [comment]
The reason the cookie policy includes its own modal styling from a pinned version of Vanilla is to prevent wild differences in Vanilla version causes huge issues across projects. The styles used by the cookie policy are namespaced to the cookie policy and so *should* trump any local styling. This of course does not defend against the introduction of new styling which the cookie policy version cannot prevent affecting it.

Cookie policy project should be kept up to date with Vanilla releases but there will be times it slips. Even with the change to renovate. Due to the release process.

**Comment by bartaz** [comment]
The styles in cookie policy are namespaced, but they are still affected by Vanilla from projects.

Like in the modal example, it has styles from cookie policy CSS, but also styles from Vanilla from project, and they misalign, so having local CSS doesn't really solve the issue, but possibly makes it happen less (?)

**Comment by anthonydillon** [comment]
Yeah exactly, no way (without scoped components) to stop the project styling from affecting a styling not specified by the cookie policy or its use of Vanilla. But I think that is likely to be an edge case.

**Comment by bartaz** [comment]
Still bit of a pity to have all our projects practically have Vanilla base duplicated in stylesheets because of cookie-policy including it's own version of it.

**Comment by anthonydillon** [comment]
Oh I only include a very small subset version of components needs. The CSS is in single figure kbs.

**Comment by bartaz** [comment]
It does include whole base of Vanilla: 

https://github.com/canonical-web-and-design/cookie-policy/blob/ec6ac0ae9dd4473ada2b2e207c81e42e24a43838/src/sass/cookie-policy.scss#L10

But its good to hear it's relatively small by itself.

Ok. I don't think we can solve it better than it is for now. With updated renovate config it should minimize the window when issues may happen.
