### ISSUE TITLE
The essential cookie is not set

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/cookie-policy#177]
The essential selection is not saved anymore. This means people see the colour policy every page visit.

## To Reproduce
1. Visit ubuntu.com clear your cookies and refresh. 
2. Click manage cookie preferences. 
3. Do not select any and save so accepting essential cookie. 
4. Refresh the page and see the colour policy appears again. 
5. Check there is no `_accept_cookie` cookie set. 

## Expected
1. Accepting no extra policy should set the cookie to the value of `essential`

**Comment by mtruj013** [comment]
Fixed in https://github.com/canonical/cookie-policy/pull/178, closing
