### ISSUE TITLE
Cookie policy includes generic styles

### ISSUE THREAD

**Issue by huwshimi** [canonical-web-and-design/cookie-policy#42]
When used in the jaas.ai project the styles included by `cookie-policy.scss` contain generic classes and are overriding the styles for `p` tags etc.

See: https://github.com/canonical-web-and-design/jaas.ai/issues/250 and my fix here: https://github.com/canonical-web-and-design/jaas.ai/pull/260/files

**Comment by anthonydillon** [comment]
This is resolved in version 2.0.1.
