### ISSUE TITLE
Set SameSite when setting cookie

### ISSUE THREAD

**Issue by anthonydillon** [canonical-web-and-design/cookie-policy#79]
Cookie “_cookies_accepted” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by pmahnke** [comment]
@anthonydillon if we do `Samesite=Lax;` it will work on local host and demos, if we do `Samesite=Strict; Secure` it will only work on https sites.  What were you thinking?

**Comment by anthonydillon** [comment]
Yeah that's important. `Lax` looks like the best option.
