### ISSUE TITLE
Dialog not spanning full fixed width, leaving slivers of arbitrary content visible

### ISSUE THREAD

**Issue by lyubomir-popov** [canonical-web-and-design/cookie-policy#82]
Maybe there's a reason, if so please ignore this, but...

![image](https://user-images.githubusercontent.com/2741678/95065169-98ca8f80-06f8-11eb-9f4c-244307932611.png)

Wouldn't it be better to make the dialog cover the content underneath? As it stand it leaves a couple of characters visible on one side (in this particular example) and looks strange. Also the hr extends further to the right so the dialog feels off center (due to differences in padding on the sidenav and main content I assume).

**Comment by anthonydillon** [comment]
This was done on purpose to make it clear that this popup is not part of the content. If the panel is row width then it looks like part of the content until you scroll and then its a jarring experience.

If you feel this is not an issue we can do it?

**Comment by lyubomir-popov** [comment]
Well, I can understand the reasoning, but I'm not convinced it is the best solution. I've seen sites do a good job of separating it from the main content in less intrusive ways, e.g. gov.uk and the bbc. If (for whatever reason) you do not want to accept, then the notices are far less intrusive if they are relatively positioned and you can scroll past:

![image](https://user-images.githubusercontent.com/2741678/95188459-5a9aa200-07c4-11eb-8a9d-80ab5b91c32c.png)
![image](https://user-images.githubusercontent.com/2741678/95188481-61291980-07c4-11eb-902d-d980d5d0e11a.png)

**Comment by anthonydillon** [comment]
Thanks @lyubomir-popov are you proposing we go full width with the panel and push the top of the page down?

**Comment by lyubomir-popov** [comment]
I think it is worth proposing. Haven't done much thinking, and the suggestions below can surely be improved, but maybe something like this?

![image](https://user-images.githubusercontent.com/2741678/95210643-a01a9780-07e3-11eb-8e92-d164de480ed0.png)

Or this, to minimise vertical height by moving heading buttons into an adjacent column. Also the stacked heading makes it quite different from normal page content, so I think that helps in making it stand out a bit more:

![image](https://user-images.githubusercontent.com/2741678/95212797-fbe62000-07e5-11eb-8f42-97a30ecf66c4.png)

The benefit in my mind is that if you refuse to accept the site is still useable, you don't have a fixed block on top of the content.

cc @spencerbygraves

**Comment by spencerbygraves** [comment]
I'm fine with it being at the top of the screen.

I don't think "tracker" is a nice term to use, don't most sites say "tell us you accept cookies" or similar?

**Comment by anthonydillon** [comment]
Ok, I can do that in the next version.

**Comment by anthonydillon** [comment]
My worry is it bites up on pushing content down which comes up a lot, that's all.

**Comment by spencerbygraves** [comment]
@anthonydillon @lyubomir-popov feel free to get a UX opinion if necessary.

**Comment by lyubomir-popov** [comment]
@clagom can we get a UX opinion? 

@anthonydillon is the copy from legal?  I assume no rewording or shortening is possible?

The bbc have done an excelent job of reducing it to 80px or so, and their copy is much less verbose, just wondering if there's more we can do in that direction rather than overlapping content.

**Comment by anthonydillon** [comment]
@cassiocassio What do you think?

**Comment by anthonydillon** [comment]
> @anthonydillon is the copy from legal? I assume no rewording or shortening is possible?


The copy was derived in conjunction by Martin and Legal.

**Comment by cassiocassio** [comment]
I shortened and humanised / simplified the wording from legal a little and got their +1, without a radical rewrite - I assumed work and thought had gone into it already. 

The choice between (A) float over the content vs (B) Glue a full width banner comes down to the behaviour you want to encourage.

The banner you tend to scroll past – makes it easy to -not- make a choice either way, and to live with it on the next page, and on return visits.

The intent of the float, the getting in the way, is to get them to make that choice, so we can record that preference and get the ridiculous popup out of the way.

Neither are great, - and I would be interested in data comparing the two - but I would like to encourage them to make that choice, so we can hide the thing, and not show it again.

25% of our users are returning and the average session is 2.5 pages / 2:50 m:ss - which is high, so I think theyre a realtively committed bunch, and encouraging that clicking-to hide over scrolling-to-slide-off-the-top is the right thing to do.

Visually: I agree the clipped content around the edge is irritating and I might increase that space, but this pop-up is -meta- to the actual content, and I don't want to do the honour or including it in the main flat plane of the page.

So I tend towards A.

**Comment by cassiocassio** [comment]
Trivial ergonomic note: if you want to encourage the click, it's faster/easier on mobile (i know we're only 20% mobile) if the buttons are near the bottom than the top. If you have to reach up, you'll probably scroll instead.

**Comment by clagom** [comment]
I've seen and interacted with both options around, if the intent is to make uses make a choice then yes A would be more effective. That said, B being sticky could also do that and you can scroll the content. But A seems easier in that sense.

**Comment by lyubomir-popov** [comment]
I see, that makes sense. Closing then.
