### ISSUE TITLE
Text doesn't flow to fill container on largest breakpoint

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/cookie-policy#91]
![Screen Shot 2020-10-10 at 12 34 21 PM](https://user-images.githubusercontent.com/532033/95753753-4987e000-0c5f-11eb-82dc-4231f43c4a41.png)

The text should either flow to the full width or the container shouldn't be as wide.

**Comment by SirSamTumless** [comment]
This is following the Vanilla pattern.

**Comment by lyubomir-popov** [comment]
Long lines are considered harder to follow, 9-12 words is generally considered optimal, and this is what dictates paragraph max-width. 

That said, I agree the screenshot above doesn't look right - the problems I see are:

- popover padding - large content makes the 1rem margins look tiny by comparison. This is something we are working to address in the [panels](https://vanillaframework.io/docs/examples/layouts/application) work. The card component is optimised for smaller pieces of content.

- the horisontal line creates an expectation that something needs to be placed in the space to the right. In my opinion a smaller popup and no line would be better.

**Comment by sowasred2012** [comment]
Closing, this appears to have been resolved: ![Screenshot from 2021-11-03 17-35-14.png](https://images.zenhubusercontent.com/5cd93aaf2406d87914830598/54c17b13-054c-43fe-8644-a2243eb2312d)
