### ISSUE TITLE
Save settings button covered by address bar in Firefox Android

### ISSUE THREAD

**Issue by hatched** [canonical-web-and-design/cookie-policy#92]
![RPtLw-xHF5-SsSxD27f2rFlUvWAYzYDVrgZPoD1zcJRm2xb4LQd3cWshMHd5Q4jntISgauhuBjkUZbYOECGShj6m2foqWeKnzVv3v50_VGgi0AzGewxn4p1fOdJfVNB3l4NOa4Tzg7HWum3db91cOupOZnsC33QRK453BIxA-K7oaeMYBNp-T4lRXKF6T1dRWqzsiUu-piwyFEKq3pbz9FJIiZLPiHI](https://user-images.githubusercontent.com/532033/97311193-b7203880-1829-11eb-80c7-ec7a2d8c5439.jpg)

**Comment by anthonydillon** [comment]
Unassigning myself as it's not sure this iteration but will take a look at this soon

**Comment by anthonydillon** [comment]
Sorry it took a year but got to it :+1:
